#!/bin/bash

. $(dirname $(readlink -f ${0}))/conf

for ((i=0; i < ${NINTERFACES}; i++)) do
    ip netns del ${NETNS_PREFIX}${i}
    ip link del ${IFACE_PREFIX}${i}
done

ip link del ${IFACE_PREFIX}ctrl

true
