#!/bin/bash
set -e

# Usage:
#   ./setup <interface> [# of routes] [update timer] [timeout timer] [garbage timer]

if [ -z "${1}" ]; then
    echo Please specify the main network interface connected to the device.
    exit 1
fi
IFACE=${1}

if [ -z "${3}" ]; then
    echo "Using the default update timer (3s)."
    UPDATE_TIMER=3
else
    UPDATE_TIMER=${3}
fi

if [ -z "${4}" ]; then
    echo "Using the default timeout timer (30s)."
    TIMEOUT_TIMER=30
else
    TIMEOUT_TIMER=${4}
fi

if [ -z "${5}" ]; then
    echo "Using the default garbage timer (60s)."
    GARBAGE_TIMER=60
else
    GARBAGE_TIMER=${5}
fi

if [ -z "${2}" ]; then
    echo "Running without RIPng rate limit."
    LIMIT=
else
    echo "Running with RIPng rate limit:"
    LIMIT=`./scripts/calc-tc.py ${2} ${UPDATE_TIMER}`
fi

. $(dirname $(readlink -f ${0}))/conf

function gen_bird {
    i=${1}; shift
    iface=${1}; shift

    cat >./conf/bird-${i}.conf <<EOF
# bird2

# random router id
router id 10.0.${i}.254;

protocol device {

}

protocol kernel {
    learn;
    persist off;
    ipv6 {
        import none;
        export none;
    };

    metric 1024;
}

protocol direct {
    ipv6;
    interface "${iface}";
}

protocol static {
    ipv6 {
        import filter {
            rip_metric = 2;
            accept;
        };
        export none;
    };
    include "rib-${i}.conf";
}

protocol rip ng {
    ipv6 {
        import all;
        export all;
    };
    #debug all;
    interface "${iface}" {
        update time ${UPDATE_TIMER};
        timeout time ${TIMEOUT_TIMER};
        garbage time ${GARBAGE_TIMER};
    };
}
EOF

    touch ./conf/rib-${i}.conf
}

cd $(dirname $(dirname $(readlink -f ${0})))
mkdir -p conf

./scripts/clean
sleep 0.5

for ((i=0; i < ${NINTERFACES}; i++)) do
    ip link add link ${IFACE} name ${IFACE_PREFIX}${i} type vlan id $((${BASE_VLAN} + ${i}))
    ip netns add ${NETNS_PREFIX}${i}
    ip link set ${IFACE_PREFIX}${i} netns ${NETNS_PREFIX}${i}
    ip netns exec ${NETNS_PREFIX}${i} ip link set lo up
    ip netns exec ${NETNS_PREFIX}${i} ip link set ${IFACE_PREFIX}${i} up
    ip netns exec ${NETNS_PREFIX}${i} ip addr
    if [ ! -z "${LIMIT}" ]; then
        ip netns exec ${NETNS_PREFIX}${i} ./scripts/setup-tc ${IFACE_PREFIX}${i} ${LIMIT}
    fi
    gen_bird ${i} ${IFACE_PREFIX}${i}
done

ip link add link ${IFACE} name ${IFACE_PREFIX}ctrl type vlan id ${CTRL_VLAN}
ip link set ${IFACE_PREFIX}ctrl up
ip addr add ${CLIENT_IP}/24 dev ${IFACE_PREFIX}ctrl
arping -c 1 -I ${IFACE_PREFIX}ctrl ${SERVER_IP}
