#!/bin/bash

NS=tanlabs-test
OUT_PREFIX=tanlabs-

IP_PREFIX=2a0e:aa06:497:

ip netns del ${NS}
ip netns add ${NS}
ip netns exec ${NS} bash -c "echo 1 > /proc/sys/net/ipv6/conf/all/forwarding"
ip netns exec ${NS} ip link set lo up
for ((i = 0; i < 4; i++)) do
    ip link add veth${i} type veth peer name ${OUT_PREFIX}veth${i}
    ip link set veth${i} netns ${NS}
    ip netns exec ${NS} ip link set veth${i} up
    i5=$((${i} + 5))
    ip netns exec ${NS} ip link set veth${i} addr 8c:1f:64:69:10:0${i5}
    ip netns exec ${NS} ip addr flush dev veth${i}
    ip netns exec ${NS} ip addr add fe80::8e1f:64ff:fe69:100${i5}/64 dev veth${i}
    ip netns exec ${NS} ip addr add ${IP_PREFIX}${i}::1/64 dev veth${i}
    ip link set ${OUT_PREFIX}veth${i} up
    i1=$((${i} + 1))
    ip link set ${OUT_PREFIX}veth${i} addr 8c:1f:64:69:10:0${i1}
    ip addr flush dev ${OUT_PREFIX}veth${i}
    ip addr add fe80::8e1f:64ff:fe69:100${i1}/64 dev ${OUT_PREFIX}veth${i}
    ip addr add ${IP_PREFIX}${i}::2/64 dev ${OUT_PREFIX}veth${i}
done

ip netns exec ${NS} ip route add 2000::/3 via fe80::8e1f:64ff:fe69:1004 dev veth3

echo In namespace ${NS}:
echo -n net.ipv6.conf.all.forwarding=
ip netns exec ${NS} cat /proc/sys/net/ipv6/conf/all/forwarding
ip netns exec ${NS} ip addr
ip netns exec ${NS} ip -6 route
echo ==========================
echo
echo Outside:
ip addr show type veth
ip -6 route | grep ${OUT_PREFIX}
echo ==========================
